language: node_js
node_js:
- 8.9.4
cache:
  yarn: true
  directories: "— node_modules"
branches:
  only:
  - master
deploy:
  provider: heroku
  app: pa11y-dash
  api_key:
    secure: QktDoJ70qvk8ADAX9PrFUOIbhjOeZOPMFdiQpwWgNUTTSDbCnqp6Y93dbFAvETgS4hg2/UmXkjtohtiVgEstbCCRcZ3UInx76e2HBAxXCB3BwrcsxF8K9IROfhidyvA+qtL4LWdQewMQ2KVyU3bHgKQ379jQ6vXxU0AGFG0sT+kx+/o8ArB2btQmmbbK7yRLLsm3+2BpnYIxXpZWLJKMgTQaAig+kqGCiP+i+7dQA5LUemXmw2gNHkcgAbw4oZf4m4/ymE+xZhkv0H7W1j0RVLEIj9hcKgeUKNYLZS1ePrVcccQo30+NYgxvTKN9llDFfD6NEoMLA7MAzmcXk36pKuTjR43T+e6dob5KsZV1L64RKnixxumD08m1aJXlWubnb4KB+tIGXwAxSbgYUY7RNLjUrZd+Nwa+ClRUZc0Yxh2iFB7oX9wUZKa3VzVS/SKwfQGVxwQtyf8RyRowUcwU/D/+nPzN40lxWM4OoT6KJFUnm2LWx4arWvgp1bBW6cv5PCb9x6Dc2vCznMVSPvS/uoeYpkHmX8GT0FUgwItxs+3Hy9PHEQD6FzVt60Rf37dE7agi+g5P4JM+zT1+2GrP5jUvHoJS7XU+7UkHAmX5vCJ2ltsJAi93k1Rcy/ci9DEuVWxewONDs6tshXlZudJmmntKh9BC/0I4DcEaWYnDTCk=
