language: node_js
node_js:
- 12.13.1
cache:
  yarn: true
  directories: "— node_modules"
branches:
  only:
  - master
deploy:
  provider: heroku
  app: pa11y-dash
  api_key:
    secure: pPo+nSGpARebwcwBkbXug+Xn5nvY+CSb9ip5LVm0LO7kvI21gP42dWtiNCMFS+zPqQq1NvTlWFW+1eFPw10iHmkX2Z3G88Aw39+neAEatsxO5ZqLioexGJ1/ZQTj2PvnRBlFKCrce+Ne1UcDqikUUR91g8FkKBW/LuI81eEILnEsxStUQ8IPPur5WqqnVNc58jDHyN3LKXlAUYI+x0Va+o4sevX7cfBPhUm0c/TNUjMpsp8KX2r1lFMWOUATZypI/M++cPW8pfX+M73kutmsR9gwN6oGcJAceL2tUvJACAPhAhPlSQIDxDlz3uqx3V4Njw/grea3R/umM2p/pe63XU6vLT800+KS+MEgiv+X+v6CrgN3ydWrqglutphsVpB6NcIBi9e6BOkuIye7D9BilvqnTuukSohf2A9RvdBmCX9RpTzbyw20ASaDNCZ0z7a2NkqbjLpnoN2OcuAt5tyqTWGmiLxS3+Ky9SwmcJ1A1p80eIetonmr28BpZoS+n7OMvEzSdYKdlp2yzuZzwK2qAVvtPxPrjl6OE914Vk8wJHVQgnE3vk3WJjqMD+e6vc2VGZnEpFm8M1KIOL/GfH82sAmpWbVAkzcJwg7Bd7C3zpsyARQy4ShyuTutLnBE1yCKRgj+QM8eSoddb8mAQUn1zT4geqdNZECAYCQUcfGF09U=
