language: node_js
node_js:
- 8.9.4
cache:
  yarn: true
  directories: "— node_modules"
branches:
  only:
  - master
services:
- mongodb
deploy:
  api_key:
    secure: X/13WHAqPfbE649DVarkG1m2aI2kPOwePBA8YkL8ul7JxNKJVIT76uhvI1S5/9tz/nt4WqhGkIjK6ngS7YUYoQfS7Zef0H0DXwidY/DFAr74Tt7jso//DDJyt98LAUvYzjfb/pGryUQwrVTutStopE6RGgpJFMSw29dzpSgSbzMROKUysll55qcIHrhMKwoOT1Dh/UJQNLAThwl+gDLG1AD5mf2lt6lltd+Kn/4j6ZaCc+2JV74TgU7vg0DWUT0oywLsB5X5RRZ3SjFwpsSJR5a/JzmqTgPZ0KXC0clBNg6A+sR5HkWAp81Qj9EoESj00x7zc5YImcKpt+SsDQjlZ5/DYBwMKrBpc1RY27mpfPNThyWzkYdWflfzBDfbB7eWzJf96h6gIkw4YWXyv/1ZasJBXPrmFS7APYEFoMkdg+cSXWsTLcZUb1+ujILTJEdY4CQKm7zJ1HlNGBWH4yF/BCQlaZCLX5riIH3M2ze0fR6BWzMsP3Imxac/vIR38JOnyKP4AOzMVaMBksw6hsUBMvxDmwsvFLBMqrBckXt+Q6ijvSV0inleElpCdIJ+F8irxwYrImMPqGYja7eYe2sl1jx4AnvCGgUZyEug96yBxcA8yG6uykOE2dnTQjaB9qoONFVxMlQV/Zvtck0e89Ny7CcwtE9UMzsQ0sUdnoEYZOk=
